# Generated by Django 3.2 on 2021-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(default=True, upload_to='Blog/images'),
        ),
    ]
