# Generated by Django 3.2 on 2021-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('images', models.ImageField(upload_to='PortFolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
