# Generated by Django 3.2 on 2021-06-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortFolio',
            new_name='Project',
        ),
    ]
